In [1]:
# %pip install pandas numpy

In [2]:
import pandas as pd
import numpy as np

In [3]:
orders = pd.DataFrame({
    "order_id": range(1001, 1011),
    "user_id": [1,2,1,3,2,4,5,3,1,4],
    "product": ["Laptop","Phone","Mouse","Keyboard","Phone",
                "Laptop","Tablet","Mouse","Laptop","Tablet"],
    "price": [70000,30000,1500,2000,30000,70000,25000,1500,70000,25000],
    "quantity": [1,1,2,1,1,1,1,3,1,2],
    "order_date": pd.date_range("2024-01-01", periods=10, freq="D")
})

In [4]:
df = pd.DataFrame({
    "user_id": [1,2,3,4,5],
    "name": ["Amit","Riya","Kunal","Neha","Sanjay"],
    "city": ["Delhi","Mumbai","Delhi","Pune","Mumbai"],
    "age": [24,27,22,29,31],
    "signup_date": pd.to_datetime(
        ["2023-11-10","2023-12-05","2024-01-15","2023-10-20","2024-01-01"]
    )
})

In [5]:
df.head()
df.tail()
df.sample(5)
df.shape
df.columns
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   user_id      5 non-null      int64
 1   name         5 non-null      object
 2   city         5 non-null      object
 3   age          5 non-null      int64
 4   signup_date  5 non-null      datetime64[ns]
dtypes: datetime64[ns](1), int64(2), object(2)
memory usage: 328.0+ bytes

        user_id        age          signup_date
count  5.000000   5.000000                    5
mean   3.000000  26.600000  2023-12-04 09:36:00
min    1.000000  22.000000  2023-10-20 00:00:00
25%    2.000000  24.000000  2023-11-10 00:00:00
50%    3.000000  27.000000  2023-12-05 00:00:00
75%    4.000000  29.000000  2024-01-01 00:00:00
max    5.000000  31.000000  2024-01-15 00:00:00
std    1.581139   3.646917                  NaN

In [6]:
df['age'].mean()
df['age'].median()
df['age'].mode()[0]
df['age'].std()

np.float64(3.646916505762094)

In [7]:
df.isna()
df.isna().sum()

df.dropna()
df.fillna(0)
df.fillna(df.mean(numeric_only=True))

   user_id    name    city  age signup_date
0        1    Amit   Delhi   24  2023-11-10
1        2    Riya  Mumbai   27  2023-12-05
2        3   Kunal   Delhi   22  2024-01-15
3        4    Neha    Pune   29  2023-10-20
4        5  Sanjay  Mumbai   31  2024-01-01